### ISSUE TITLE
Set up ci

### ISSUE THREAD

**Issue by cleverer** [scout-ch/midata-cypress#2]
Maybe use travis, as upstream uses it as well

**Todo**
- [x] Action checking PRs
  - [x] Store artifacts (videos/screenshots)
- [ ] ~~Restructure compose to allow running from images (Check [here]( https://docs.docker.com/compose/extends/#example-use-case))~~
  _Not needed, as users of the repo of course can use the image as well…_
- [x] Action building the Docker image
- [x] Action running the e2e-Tests
  - [x] Push results to cypress.io
  - [x] Maybe store artifacts (videos/screenshots). However, they'll also be on cypress.io

**Comment by cleverer** [comment]
Or even better Github Actions

**Comment by cleverer** [comment]
To have speedy runs, I propose to have a job on master (and/or tags), that builds the docker container and pushes it to github packages. Then the test only spins up those services images (hitobito itself).

**Comment by carlobeltrame** [comment]
Sounds good! I think we won't have too many different branches anyway, so we can use master as the single source of truth.
